[package]
authors = ["Alexander Nikolaev <alexander.nikolaev@unikie.com>"]
edition = "2021"
license = "Apache 2.0"
name = "givc-client"
publish = false
version = "0.0.1"

[dependencies]
anyhow = "1.0.86"
async-channel = "2.3.1"
async-stream = "0.3"
hyper-util = { version = "0.1"}
tokio = {version = "1.0", features = ["rt-multi-thread", "time", "macros"]}
tokio-stream = "0.1"
tokio-vsock = "*"
tonic = {version="0.12", features = ["tls"]}
tonic-types = {version="0.12"}
tower = {version = "0.4"}
tracing = "0.1"
serde = { version = "1.0.202", features = ["derive"]}

givc-common = { path = "../common" }
