# SPDX-FileCopyrightText: 2022-2024 TII (SSRC) and the Ghaf contributors
# SPDX-License-Identifier: Apache-2.0

name: go-sectest
on:
    push:
        paths:
        - 'modules/**'
    pull_request:
        paths:
        - 'modules/**'
permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout Source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run Gosec Security Scanner
        uses: securego/gosec@d2d3ae66bd8d340b78b5142b6fe610691783c2fe # master
        with:
          args: '-exclude=G302,G204 -no-fail ./modules/...'
      - name: Run Go Tests
        run: go test -v ./modules/...